{% set name = "django-tenant-users" %}
{% set version = "2.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/django_tenant_users-{{ version }}.tar.gz
  sha256: 84607b1b64eaab8989098a50da372790467c76f9c9a584e4a0bf617db9452141

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - poetry-core >=1.2.0
    - pip
  run:
    - python >={{ python_min }},<4.0.0
    - django >=4.2
    - django-tenants <4.0,>=3.6
    # - Django >=4.2
    # - Django >=4.2

test:
  imports:
    - tenant_users
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://www.github.com/Corvia/django-tenant-users
  summary: A Django app to extend django-tenants to incorporate global multi-tenant users
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
