{% set name = "django-tenant-users" %}
{% set version = "1.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/django_tenant_users-{{ version }}.tar.gz
  sha256: c9913f5ebecf55cc93f586ea05c98f4c347758c537850374c7892ca452535877

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7.0,<4.0.0
    - poetry-core >=1.2.0
    - pip
  run:
    - python >=3.7.0,<4.0.0
    - django >=3.2
    - django-tenants >=3.4.5,<4.0.0

test:
  imports:
    - tenant_users
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://www.github.com/Corvia/django-tenant-users
  summary: A Django app to extend django-tenants to incorporate global multi-tenant users
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
