{% set name = "django-tenant-users" %}
{% set version = "2.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/django_tenant_users-{{ version }}.tar.gz
  sha256: f13a5cf55b42197815738e65cb90f20b040621178d62d30bf200f00cbc0264df

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - poetry-core >=1.2.0
    - pip
  run:
    - python >={{ python_min }},<4.0.0
    - django >=4.2
    - django-tenants >=3.6.0,<4.0.0
    # - Django >=4.2

test:
  imports:
    - tenant_users
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://www.github.com/Corvia/django-tenant-users
  summary: A Django app to extend django-tenants to incorporate global multi-tenant users
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
